package model

// Code generated by tools/gensqs. DO NOT EDIT.

func init() {
	Default = Registry{}
	const raw = `{
	"metadata": {
		"apiVersion": "2012-11-05",
		"endpointPrefix": "sqs",
		"jsonVersion": "1.0",
		"protocol": "json",
		"targetPrefix": "AmazonSQS",
		"queryNamespace": "http://queue.amazonaws.com/doc/2012-11-05/",
		"serviceId": "SQS"
	},
	"operations": {
		"AddPermission": {
			"name": "AddPermission",
			"inputShape": "AddPermissionRequest",
			"errors": [
				"OverLimit",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidAddress",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"CancelMessageMoveTask": {
			"name": "CancelMessageMoveTask",
			"inputShape": "CancelMessageMoveTaskRequest",
			"outputShape": "CancelMessageMoveTaskResult",
			"errors": [
				"ResourceNotFoundException",
				"RequestThrottled",
				"InvalidAddress",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"ChangeMessageVisibility": {
			"name": "ChangeMessageVisibility",
			"inputShape": "ChangeMessageVisibilityRequest",
			"errors": [
				"MessageNotInflight",
				"ReceiptHandleIsInvalid",
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"InvalidAddress",
				"InvalidSecurity"
			]
		},
		"ChangeMessageVisibilityBatch": {
			"name": "ChangeMessageVisibilityBatch",
			"inputShape": "ChangeMessageVisibilityBatchRequest",
			"outputShape": "ChangeMessageVisibilityBatchResult",
			"errors": [
				"TooManyEntriesInBatchRequest",
				"EmptyBatchRequest",
				"BatchEntryIdsNotDistinct",
				"InvalidBatchEntryId",
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"InvalidAddress",
				"InvalidSecurity"
			]
		},
		"CreateQueue": {
			"name": "CreateQueue",
			"inputShape": "CreateQueueRequest",
			"outputShape": "CreateQueueResult",
			"errors": [
				"QueueDeletedRecently",
				"QueueNameExists",
				"RequestThrottled",
				"InvalidAddress",
				"InvalidAttributeName",
				"InvalidAttributeValue",
				"UnsupportedOperation",
				"InvalidSecurity"
			]
		},
		"DeleteMessage": {
			"name": "DeleteMessage",
			"inputShape": "DeleteMessageRequest",
			"errors": [
				"InvalidIdFormat",
				"ReceiptHandleIsInvalid",
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"InvalidSecurity",
				"InvalidAddress"
			]
		},
		"DeleteMessageBatch": {
			"name": "DeleteMessageBatch",
			"inputShape": "DeleteMessageBatchRequest",
			"outputShape": "DeleteMessageBatchResult",
			"errors": [
				"TooManyEntriesInBatchRequest",
				"EmptyBatchRequest",
				"BatchEntryIdsNotDistinct",
				"InvalidBatchEntryId",
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"InvalidAddress",
				"InvalidSecurity"
			]
		},
		"DeleteQueue": {
			"name": "DeleteQueue",
			"inputShape": "DeleteQueueRequest",
			"errors": [
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidAddress",
				"UnsupportedOperation",
				"InvalidSecurity"
			]
		},
		"GetQueueAttributes": {
			"name": "GetQueueAttributes",
			"inputShape": "GetQueueAttributesRequest",
			"outputShape": "GetQueueAttributesResult",
			"errors": [
				"InvalidAttributeName",
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"InvalidSecurity",
				"InvalidAddress"
			]
		},
		"GetQueueUrl": {
			"name": "GetQueueUrl",
			"inputShape": "GetQueueUrlRequest",
			"outputShape": "GetQueueUrlResult",
			"errors": [
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidAddress",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"ListDeadLetterSourceQueues": {
			"name": "ListDeadLetterSourceQueues",
			"inputShape": "ListDeadLetterSourceQueuesRequest",
			"outputShape": "ListDeadLetterSourceQueuesResult",
			"errors": [
				"QueueDoesNotExist",
				"RequestThrottled",
				"InvalidSecurity",
				"InvalidAddress",
				"UnsupportedOperation"
			]
		},
		"ListMessageMoveTasks": {
			"name": "ListMessageMoveTasks",
			"inputShape": "ListMessageMoveTasksRequest",
			"outputShape": "ListMessageMoveTasksResult",
			"errors": [
				"ResourceNotFoundException",
				"RequestThrottled",
				"InvalidAddress",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"ListQueueTags": {
			"name": "ListQueueTags",
			"inputShape": "ListQueueTagsRequest",
			"outputShape": "ListQueueTagsResult",
			"errors": [
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"InvalidAddress",
				"InvalidSecurity"
			]
		},
		"ListQueues": {
			"name": "ListQueues",
			"inputShape": "ListQueuesRequest",
			"outputShape": "ListQueuesResult",
			"errors": [
				"RequestThrottled",
				"InvalidSecurity",
				"InvalidAddress",
				"UnsupportedOperation"
			]
		},
		"PurgeQueue": {
			"name": "PurgeQueue",
			"inputShape": "PurgeQueueRequest",
			"errors": [
				"QueueDoesNotExist",
				"PurgeQueueInProgress",
				"RequestThrottled",
				"InvalidAddress",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"ReceiveMessage": {
			"name": "ReceiveMessage",
			"inputShape": "ReceiveMessageRequest",
			"outputShape": "ReceiveMessageResult",
			"errors": [
				"UnsupportedOperation",
				"OverLimit",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidSecurity",
				"KmsDisabled",
				"KmsInvalidState",
				"KmsNotFound",
				"KmsOptInRequired",
				"KmsThrottled",
				"KmsAccessDenied",
				"KmsInvalidKeyUsage",
				"InvalidAddress"
			]
		},
		"RemovePermission": {
			"name": "RemovePermission",
			"inputShape": "RemovePermissionRequest",
			"errors": [
				"InvalidAddress",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"SendMessage": {
			"name": "SendMessage",
			"inputShape": "SendMessageRequest",
			"outputShape": "SendMessageResult",
			"errors": [
				"InvalidMessageContents",
				"UnsupportedOperation",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidSecurity",
				"KmsDisabled",
				"KmsInvalidState",
				"KmsNotFound",
				"KmsOptInRequired",
				"KmsThrottled",
				"KmsAccessDenied",
				"KmsInvalidKeyUsage",
				"InvalidAddress"
			]
		},
		"SendMessageBatch": {
			"name": "SendMessageBatch",
			"inputShape": "SendMessageBatchRequest",
			"outputShape": "SendMessageBatchResult",
			"errors": [
				"TooManyEntriesInBatchRequest",
				"EmptyBatchRequest",
				"BatchEntryIdsNotDistinct",
				"BatchRequestTooLong",
				"InvalidBatchEntryId",
				"UnsupportedOperation",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidSecurity",
				"KmsDisabled",
				"KmsInvalidState",
				"KmsNotFound",
				"KmsOptInRequired",
				"KmsThrottled",
				"KmsAccessDenied",
				"KmsInvalidKeyUsage",
				"InvalidAddress"
			]
		},
		"SetQueueAttributes": {
			"name": "SetQueueAttributes",
			"inputShape": "SetQueueAttributesRequest",
			"errors": [
				"InvalidAttributeName",
				"InvalidAttributeValue",
				"RequestThrottled",
				"QueueDoesNotExist",
				"UnsupportedOperation",
				"OverLimit",
				"InvalidAddress",
				"InvalidSecurity"
			]
		},
		"StartMessageMoveTask": {
			"name": "StartMessageMoveTask",
			"inputShape": "StartMessageMoveTaskRequest",
			"outputShape": "StartMessageMoveTaskResult",
			"errors": [
				"ResourceNotFoundException",
				"RequestThrottled",
				"InvalidAddress",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"TagQueue": {
			"name": "TagQueue",
			"inputShape": "TagQueueRequest",
			"errors": [
				"InvalidAddress",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		},
		"UntagQueue": {
			"name": "UntagQueue",
			"inputShape": "UntagQueueRequest",
			"errors": [
				"InvalidAddress",
				"RequestThrottled",
				"QueueDoesNotExist",
				"InvalidSecurity",
				"UnsupportedOperation"
			]
		}
	},
	"shapes": {
		"AWSAccountIdList": {
			"name": "AWSAccountIdList",
			"type": "list",
			"member": {
				"shape": "String"
			},
			"flattened": true
		},
		"ActionNameList": {
			"name": "ActionNameList",
			"type": "list",
			"member": {
				"shape": "String"
			},
			"flattened": true
		},
		"AddPermissionRequest": {
			"name": "AddPermissionRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Label",
				"AWSAccountIds",
				"Actions"
			],
			"memberOrder": [
				"AWSAccountIds",
				"Actions",
				"Label",
				"QueueUrl"
			],
			"members": {
				"AWSAccountIds": {
					"shape": "AWSAccountIdList"
				},
				"Actions": {
					"shape": "ActionNameList"
				},
				"Label": {
					"shape": "String"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"AttributeNameList": {
			"name": "AttributeNameList",
			"type": "list",
			"member": {
				"shape": "QueueAttributeName"
			},
			"flattened": true
		},
		"BatchEntryIdsNotDistinct": {
			"name": "BatchEntryIdsNotDistinct",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"BatchRequestTooLong": {
			"name": "BatchRequestTooLong",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"BatchResultErrorEntry": {
			"name": "BatchResultErrorEntry",
			"type": "structure",
			"required": [
				"Id",
				"SenderFault",
				"Code"
			],
			"memberOrder": [
				"Code",
				"Id",
				"Message",
				"SenderFault"
			],
			"members": {
				"Code": {
					"shape": "String"
				},
				"Id": {
					"shape": "String"
				},
				"Message": {
					"shape": "String"
				},
				"SenderFault": {
					"shape": "Boolean"
				}
			}
		},
		"BatchResultErrorEntryList": {
			"name": "BatchResultErrorEntryList",
			"type": "list",
			"member": {
				"shape": "BatchResultErrorEntry"
			},
			"flattened": true
		},
		"Binary": {
			"name": "Binary",
			"type": "blob"
		},
		"BinaryList": {
			"name": "BinaryList",
			"type": "list",
			"member": {
				"shape": "Binary"
			}
		},
		"Boolean": {
			"name": "Boolean",
			"type": "boolean"
		},
		"BoxedInteger": {
			"name": "BoxedInteger",
			"type": "integer"
		},
		"CancelMessageMoveTaskRequest": {
			"name": "CancelMessageMoveTaskRequest",
			"type": "structure",
			"required": [
				"TaskHandle"
			],
			"memberOrder": [
				"TaskHandle"
			],
			"members": {
				"TaskHandle": {
					"shape": "String"
				}
			}
		},
		"CancelMessageMoveTaskResult": {
			"name": "CancelMessageMoveTaskResult",
			"type": "structure",
			"memberOrder": [
				"ApproximateNumberOfMessagesMoved"
			],
			"members": {
				"ApproximateNumberOfMessagesMoved": {
					"shape": "Long"
				}
			}
		},
		"ChangeMessageVisibilityBatchRequest": {
			"name": "ChangeMessageVisibilityBatchRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Entries"
			],
			"memberOrder": [
				"Entries",
				"QueueUrl"
			],
			"members": {
				"Entries": {
					"shape": "ChangeMessageVisibilityBatchRequestEntryList"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"ChangeMessageVisibilityBatchRequestEntry": {
			"name": "ChangeMessageVisibilityBatchRequestEntry",
			"type": "structure",
			"required": [
				"Id",
				"ReceiptHandle"
			],
			"memberOrder": [
				"Id",
				"ReceiptHandle",
				"VisibilityTimeout"
			],
			"members": {
				"Id": {
					"shape": "String"
				},
				"ReceiptHandle": {
					"shape": "String"
				},
				"VisibilityTimeout": {
					"shape": "NullableInteger"
				}
			}
		},
		"ChangeMessageVisibilityBatchRequestEntryList": {
			"name": "ChangeMessageVisibilityBatchRequestEntryList",
			"type": "list",
			"member": {
				"shape": "ChangeMessageVisibilityBatchRequestEntry"
			},
			"flattened": true
		},
		"ChangeMessageVisibilityBatchResult": {
			"name": "ChangeMessageVisibilityBatchResult",
			"type": "structure",
			"required": [
				"Successful",
				"Failed"
			],
			"memberOrder": [
				"Failed",
				"Successful"
			],
			"members": {
				"Failed": {
					"shape": "BatchResultErrorEntryList"
				},
				"Successful": {
					"shape": "ChangeMessageVisibilityBatchResultEntryList"
				}
			}
		},
		"ChangeMessageVisibilityBatchResultEntry": {
			"name": "ChangeMessageVisibilityBatchResultEntry",
			"type": "structure",
			"required": [
				"Id"
			],
			"memberOrder": [
				"Id"
			],
			"members": {
				"Id": {
					"shape": "String"
				}
			}
		},
		"ChangeMessageVisibilityBatchResultEntryList": {
			"name": "ChangeMessageVisibilityBatchResultEntryList",
			"type": "list",
			"member": {
				"shape": "ChangeMessageVisibilityBatchResultEntry"
			},
			"flattened": true
		},
		"ChangeMessageVisibilityRequest": {
			"name": "ChangeMessageVisibilityRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"ReceiptHandle",
				"VisibilityTimeout"
			],
			"memberOrder": [
				"QueueUrl",
				"ReceiptHandle",
				"VisibilityTimeout"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				},
				"ReceiptHandle": {
					"shape": "String"
				},
				"VisibilityTimeout": {
					"shape": "NullableInteger"
				}
			}
		},
		"CreateQueueRequest": {
			"name": "CreateQueueRequest",
			"type": "structure",
			"required": [
				"QueueName"
			],
			"memberOrder": [
				"Attributes",
				"QueueName",
				"tags"
			],
			"members": {
				"Attributes": {
					"shape": "QueueAttributeMap"
				},
				"QueueName": {
					"shape": "String"
				},
				"tags": {
					"shape": "TagMap"
				}
			}
		},
		"CreateQueueResult": {
			"name": "CreateQueueResult",
			"type": "structure",
			"memberOrder": [
				"QueueUrl"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"DeleteMessageBatchRequest": {
			"name": "DeleteMessageBatchRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Entries"
			],
			"memberOrder": [
				"Entries",
				"QueueUrl"
			],
			"members": {
				"Entries": {
					"shape": "DeleteMessageBatchRequestEntryList"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"DeleteMessageBatchRequestEntry": {
			"name": "DeleteMessageBatchRequestEntry",
			"type": "structure",
			"required": [
				"Id",
				"ReceiptHandle"
			],
			"memberOrder": [
				"Id",
				"ReceiptHandle"
			],
			"members": {
				"Id": {
					"shape": "String"
				},
				"ReceiptHandle": {
					"shape": "String"
				}
			}
		},
		"DeleteMessageBatchRequestEntryList": {
			"name": "DeleteMessageBatchRequestEntryList",
			"type": "list",
			"member": {
				"shape": "DeleteMessageBatchRequestEntry"
			},
			"flattened": true
		},
		"DeleteMessageBatchResult": {
			"name": "DeleteMessageBatchResult",
			"type": "structure",
			"required": [
				"Successful",
				"Failed"
			],
			"memberOrder": [
				"Failed",
				"Successful"
			],
			"members": {
				"Failed": {
					"shape": "BatchResultErrorEntryList"
				},
				"Successful": {
					"shape": "DeleteMessageBatchResultEntryList"
				}
			}
		},
		"DeleteMessageBatchResultEntry": {
			"name": "DeleteMessageBatchResultEntry",
			"type": "structure",
			"required": [
				"Id"
			],
			"memberOrder": [
				"Id"
			],
			"members": {
				"Id": {
					"shape": "String"
				}
			}
		},
		"DeleteMessageBatchResultEntryList": {
			"name": "DeleteMessageBatchResultEntryList",
			"type": "list",
			"member": {
				"shape": "DeleteMessageBatchResultEntry"
			},
			"flattened": true
		},
		"DeleteMessageRequest": {
			"name": "DeleteMessageRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"ReceiptHandle"
			],
			"memberOrder": [
				"QueueUrl",
				"ReceiptHandle"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				},
				"ReceiptHandle": {
					"shape": "String"
				}
			}
		},
		"DeleteQueueRequest": {
			"name": "DeleteQueueRequest",
			"type": "structure",
			"required": [
				"QueueUrl"
			],
			"memberOrder": [
				"QueueUrl"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"EmptyBatchRequest": {
			"name": "EmptyBatchRequest",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"ExceptionMessage": {
			"name": "ExceptionMessage",
			"type": "string"
		},
		"GetQueueAttributesRequest": {
			"name": "GetQueueAttributesRequest",
			"type": "structure",
			"required": [
				"QueueUrl"
			],
			"memberOrder": [
				"AttributeNames",
				"QueueUrl"
			],
			"members": {
				"AttributeNames": {
					"shape": "AttributeNameList"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"GetQueueAttributesResult": {
			"name": "GetQueueAttributesResult",
			"type": "structure",
			"memberOrder": [
				"Attributes"
			],
			"members": {
				"Attributes": {
					"shape": "QueueAttributeMap"
				}
			}
		},
		"GetQueueUrlRequest": {
			"name": "GetQueueUrlRequest",
			"type": "structure",
			"required": [
				"QueueName"
			],
			"memberOrder": [
				"QueueName",
				"QueueOwnerAWSAccountId"
			],
			"members": {
				"QueueName": {
					"shape": "String"
				},
				"QueueOwnerAWSAccountId": {
					"shape": "String"
				}
			}
		},
		"GetQueueUrlResult": {
			"name": "GetQueueUrlResult",
			"type": "structure",
			"memberOrder": [
				"QueueUrl"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"InvalidAddress": {
			"name": "InvalidAddress",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"InvalidAttributeName": {
			"name": "InvalidAttributeName",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"InvalidAttributeValue": {
			"name": "InvalidAttributeValue",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"InvalidBatchEntryId": {
			"name": "InvalidBatchEntryId",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"InvalidIdFormat": {
			"name": "InvalidIdFormat",
			"type": "structure",
			"exception": true
		},
		"InvalidMessageContents": {
			"name": "InvalidMessageContents",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"InvalidSecurity": {
			"name": "InvalidSecurity",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsAccessDenied": {
			"name": "KmsAccessDenied",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsDisabled": {
			"name": "KmsDisabled",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsInvalidKeyUsage": {
			"name": "KmsInvalidKeyUsage",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsInvalidState": {
			"name": "KmsInvalidState",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsNotFound": {
			"name": "KmsNotFound",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsOptInRequired": {
			"name": "KmsOptInRequired",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"KmsThrottled": {
			"name": "KmsThrottled",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"ListDeadLetterSourceQueuesRequest": {
			"name": "ListDeadLetterSourceQueuesRequest",
			"type": "structure",
			"required": [
				"QueueUrl"
			],
			"memberOrder": [
				"MaxResults",
				"NextToken",
				"QueueUrl"
			],
			"members": {
				"MaxResults": {
					"shape": "BoxedInteger"
				},
				"NextToken": {
					"shape": "Token"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"ListDeadLetterSourceQueuesResult": {
			"name": "ListDeadLetterSourceQueuesResult",
			"type": "structure",
			"required": [
				"queueUrls"
			],
			"memberOrder": [
				"NextToken",
				"queueUrls"
			],
			"members": {
				"NextToken": {
					"shape": "Token"
				},
				"queueUrls": {
					"shape": "QueueUrlList"
				}
			}
		},
		"ListMessageMoveTasksRequest": {
			"name": "ListMessageMoveTasksRequest",
			"type": "structure",
			"required": [
				"SourceArn"
			],
			"memberOrder": [
				"MaxResults",
				"SourceArn"
			],
			"members": {
				"MaxResults": {
					"shape": "NullableInteger"
				},
				"SourceArn": {
					"shape": "String"
				}
			}
		},
		"ListMessageMoveTasksResult": {
			"name": "ListMessageMoveTasksResult",
			"type": "structure",
			"memberOrder": [
				"Results"
			],
			"members": {
				"Results": {
					"shape": "ListMessageMoveTasksResultEntryList",
					"flattened": true
				}
			}
		},
		"ListMessageMoveTasksResultEntry": {
			"name": "ListMessageMoveTasksResultEntry",
			"type": "structure",
			"memberOrder": [
				"ApproximateNumberOfMessagesMoved",
				"ApproximateNumberOfMessagesToMove",
				"DestinationArn",
				"FailureReason",
				"MaxNumberOfMessagesPerSecond",
				"SourceArn",
				"StartedTimestamp",
				"Status",
				"TaskHandle"
			],
			"members": {
				"ApproximateNumberOfMessagesMoved": {
					"shape": "Long"
				},
				"ApproximateNumberOfMessagesToMove": {
					"shape": "NullableLong"
				},
				"DestinationArn": {
					"shape": "String"
				},
				"FailureReason": {
					"shape": "String"
				},
				"MaxNumberOfMessagesPerSecond": {
					"shape": "NullableInteger"
				},
				"SourceArn": {
					"shape": "String"
				},
				"StartedTimestamp": {
					"shape": "Long"
				},
				"Status": {
					"shape": "String"
				},
				"TaskHandle": {
					"shape": "String"
				}
			}
		},
		"ListMessageMoveTasksResultEntryList": {
			"name": "ListMessageMoveTasksResultEntryList",
			"type": "list",
			"member": {
				"shape": "ListMessageMoveTasksResultEntry"
			},
			"flattened": true
		},
		"ListQueueTagsRequest": {
			"name": "ListQueueTagsRequest",
			"type": "structure",
			"required": [
				"QueueUrl"
			],
			"memberOrder": [
				"QueueUrl"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"ListQueueTagsResult": {
			"name": "ListQueueTagsResult",
			"type": "structure",
			"memberOrder": [
				"Tags"
			],
			"members": {
				"Tags": {
					"shape": "TagMap"
				}
			}
		},
		"ListQueuesRequest": {
			"name": "ListQueuesRequest",
			"type": "structure",
			"memberOrder": [
				"MaxResults",
				"NextToken",
				"QueueNamePrefix"
			],
			"members": {
				"MaxResults": {
					"shape": "BoxedInteger"
				},
				"NextToken": {
					"shape": "Token"
				},
				"QueueNamePrefix": {
					"shape": "String"
				}
			}
		},
		"ListQueuesResult": {
			"name": "ListQueuesResult",
			"type": "structure",
			"memberOrder": [
				"NextToken",
				"QueueUrls"
			],
			"members": {
				"NextToken": {
					"shape": "Token"
				},
				"QueueUrls": {
					"shape": "QueueUrlList"
				}
			}
		},
		"Long": {
			"name": "Long",
			"type": "long"
		},
		"Message": {
			"name": "Message",
			"type": "structure",
			"memberOrder": [
				"Attributes",
				"Body",
				"MD5OfBody",
				"MD5OfMessageAttributes",
				"MessageAttributes",
				"MessageId",
				"ReceiptHandle"
			],
			"members": {
				"Attributes": {
					"shape": "MessageSystemAttributeMap"
				},
				"Body": {
					"shape": "String"
				},
				"MD5OfBody": {
					"shape": "String"
				},
				"MD5OfMessageAttributes": {
					"shape": "String"
				},
				"MessageAttributes": {
					"shape": "MessageBodyAttributeMap"
				},
				"MessageId": {
					"shape": "String"
				},
				"ReceiptHandle": {
					"shape": "String"
				}
			}
		},
		"MessageAttributeName": {
			"name": "MessageAttributeName",
			"type": "string"
		},
		"MessageAttributeNameList": {
			"name": "MessageAttributeNameList",
			"type": "list",
			"member": {
				"shape": "MessageAttributeName"
			},
			"flattened": true
		},
		"MessageAttributeValue": {
			"name": "MessageAttributeValue",
			"type": "structure",
			"required": [
				"DataType"
			],
			"memberOrder": [
				"BinaryListValues",
				"BinaryValue",
				"DataType",
				"StringListValues",
				"StringValue"
			],
			"members": {
				"BinaryListValues": {
					"shape": "BinaryList",
					"flattened": true
				},
				"BinaryValue": {
					"shape": "Binary"
				},
				"DataType": {
					"shape": "String"
				},
				"StringListValues": {
					"shape": "StringList",
					"flattened": true
				},
				"StringValue": {
					"shape": "String"
				}
			}
		},
		"MessageBodyAttributeMap": {
			"name": "MessageBodyAttributeMap",
			"type": "map",
			"key": {
				"shape": "String"
			},
			"value": {
				"shape": "MessageAttributeValue"
			},
			"flattened": true
		},
		"MessageBodySystemAttributeMap": {
			"name": "MessageBodySystemAttributeMap",
			"type": "map",
			"key": {
				"shape": "MessageSystemAttributeNameForSends"
			},
			"value": {
				"shape": "MessageSystemAttributeValue"
			},
			"flattened": true
		},
		"MessageList": {
			"name": "MessageList",
			"type": "list",
			"member": {
				"shape": "Message"
			},
			"flattened": true
		},
		"MessageNotInflight": {
			"name": "MessageNotInflight",
			"type": "structure",
			"exception": true
		},
		"MessageSystemAttributeList": {
			"name": "MessageSystemAttributeList",
			"type": "list",
			"member": {
				"shape": "MessageSystemAttributeName"
			},
			"flattened": true
		},
		"MessageSystemAttributeMap": {
			"name": "MessageSystemAttributeMap",
			"type": "map",
			"key": {
				"shape": "MessageSystemAttributeName"
			},
			"value": {
				"shape": "String"
			},
			"flattened": true
		},
		"MessageSystemAttributeName": {
			"name": "MessageSystemAttributeName",
			"type": "string",
			"enum": [
				"All",
				"SenderId",
				"SentTimestamp",
				"ApproximateReceiveCount",
				"ApproximateFirstReceiveTimestamp",
				"SequenceNumber",
				"MessageDeduplicationId",
				"MessageGroupId",
				"AWSTraceHeader",
				"DeadLetterQueueSourceArn"
			]
		},
		"MessageSystemAttributeNameForSends": {
			"name": "MessageSystemAttributeNameForSends",
			"type": "string",
			"enum": [
				"AWSTraceHeader"
			]
		},
		"MessageSystemAttributeValue": {
			"name": "MessageSystemAttributeValue",
			"type": "structure",
			"required": [
				"DataType"
			],
			"memberOrder": [
				"BinaryListValues",
				"BinaryValue",
				"DataType",
				"StringListValues",
				"StringValue"
			],
			"members": {
				"BinaryListValues": {
					"shape": "BinaryList",
					"flattened": true
				},
				"BinaryValue": {
					"shape": "Binary"
				},
				"DataType": {
					"shape": "String"
				},
				"StringListValues": {
					"shape": "StringList",
					"flattened": true
				},
				"StringValue": {
					"shape": "String"
				}
			}
		},
		"NullableInteger": {
			"name": "NullableInteger",
			"type": "integer"
		},
		"NullableLong": {
			"name": "NullableLong",
			"type": "long"
		},
		"OverLimit": {
			"name": "OverLimit",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"PurgeQueueInProgress": {
			"name": "PurgeQueueInProgress",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"PurgeQueueRequest": {
			"name": "PurgeQueueRequest",
			"type": "structure",
			"required": [
				"QueueUrl"
			],
			"memberOrder": [
				"QueueUrl"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"QueueAttributeMap": {
			"name": "QueueAttributeMap",
			"type": "map",
			"key": {
				"shape": "QueueAttributeName"
			},
			"value": {
				"shape": "String"
			},
			"flattened": true
		},
		"QueueAttributeName": {
			"name": "QueueAttributeName",
			"type": "string",
			"enum": [
				"All",
				"Policy",
				"VisibilityTimeout",
				"MaximumMessageSize",
				"MessageRetentionPeriod",
				"ApproximateNumberOfMessages",
				"ApproximateNumberOfMessagesNotVisible",
				"CreatedTimestamp",
				"LastModifiedTimestamp",
				"QueueArn",
				"ApproximateNumberOfMessagesDelayed",
				"DelaySeconds",
				"ReceiveMessageWaitTimeSeconds",
				"RedrivePolicy",
				"FifoQueue",
				"ContentBasedDeduplication",
				"KmsMasterKeyId",
				"KmsDataKeyReusePeriodSeconds",
				"DeduplicationScope",
				"FifoThroughputLimit",
				"RedriveAllowPolicy",
				"SqsManagedSseEnabled"
			]
		},
		"QueueDeletedRecently": {
			"name": "QueueDeletedRecently",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"QueueDoesNotExist": {
			"name": "QueueDoesNotExist",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"QueueNameExists": {
			"name": "QueueNameExists",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"QueueUrlList": {
			"name": "QueueUrlList",
			"type": "list",
			"member": {
				"shape": "String"
			},
			"flattened": true
		},
		"ReceiptHandleIsInvalid": {
			"name": "ReceiptHandleIsInvalid",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"ReceiveMessageRequest": {
			"name": "ReceiveMessageRequest",
			"type": "structure",
			"required": [
				"QueueUrl"
			],
			"memberOrder": [
				"AttributeNames",
				"MaxNumberOfMessages",
				"MessageAttributeNames",
				"MessageSystemAttributeNames",
				"QueueUrl",
				"ReceiveRequestAttemptId",
				"VisibilityTimeout",
				"WaitTimeSeconds"
			],
			"members": {
				"AttributeNames": {
					"shape": "AttributeNameList"
				},
				"MaxNumberOfMessages": {
					"shape": "NullableInteger"
				},
				"MessageAttributeNames": {
					"shape": "MessageAttributeNameList"
				},
				"MessageSystemAttributeNames": {
					"shape": "MessageSystemAttributeList"
				},
				"QueueUrl": {
					"shape": "String"
				},
				"ReceiveRequestAttemptId": {
					"shape": "String"
				},
				"VisibilityTimeout": {
					"shape": "NullableInteger"
				},
				"WaitTimeSeconds": {
					"shape": "NullableInteger"
				}
			}
		},
		"ReceiveMessageResult": {
			"name": "ReceiveMessageResult",
			"type": "structure",
			"memberOrder": [
				"Messages"
			],
			"members": {
				"Messages": {
					"shape": "MessageList"
				}
			}
		},
		"RemovePermissionRequest": {
			"name": "RemovePermissionRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Label"
			],
			"memberOrder": [
				"Label",
				"QueueUrl"
			],
			"members": {
				"Label": {
					"shape": "String"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"RequestThrottled": {
			"name": "RequestThrottled",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"ResourceNotFoundException": {
			"name": "ResourceNotFoundException",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"SendMessageBatchRequest": {
			"name": "SendMessageBatchRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Entries"
			],
			"memberOrder": [
				"Entries",
				"QueueUrl"
			],
			"members": {
				"Entries": {
					"shape": "SendMessageBatchRequestEntryList"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"SendMessageBatchRequestEntry": {
			"name": "SendMessageBatchRequestEntry",
			"type": "structure",
			"required": [
				"Id",
				"MessageBody"
			],
			"memberOrder": [
				"DelaySeconds",
				"Id",
				"MessageAttributes",
				"MessageBody",
				"MessageDeduplicationId",
				"MessageGroupId",
				"MessageSystemAttributes"
			],
			"members": {
				"DelaySeconds": {
					"shape": "NullableInteger"
				},
				"Id": {
					"shape": "String"
				},
				"MessageAttributes": {
					"shape": "MessageBodyAttributeMap"
				},
				"MessageBody": {
					"shape": "String"
				},
				"MessageDeduplicationId": {
					"shape": "String"
				},
				"MessageGroupId": {
					"shape": "String"
				},
				"MessageSystemAttributes": {
					"shape": "MessageBodySystemAttributeMap"
				}
			}
		},
		"SendMessageBatchRequestEntryList": {
			"name": "SendMessageBatchRequestEntryList",
			"type": "list",
			"member": {
				"shape": "SendMessageBatchRequestEntry"
			},
			"flattened": true
		},
		"SendMessageBatchResult": {
			"name": "SendMessageBatchResult",
			"type": "structure",
			"required": [
				"Successful",
				"Failed"
			],
			"memberOrder": [
				"Failed",
				"Successful"
			],
			"members": {
				"Failed": {
					"shape": "BatchResultErrorEntryList"
				},
				"Successful": {
					"shape": "SendMessageBatchResultEntryList"
				}
			}
		},
		"SendMessageBatchResultEntry": {
			"name": "SendMessageBatchResultEntry",
			"type": "structure",
			"required": [
				"Id",
				"MessageId",
				"MD5OfMessageBody"
			],
			"memberOrder": [
				"Id",
				"MD5OfMessageAttributes",
				"MD5OfMessageBody",
				"MD5OfMessageSystemAttributes",
				"MessageId",
				"SequenceNumber"
			],
			"members": {
				"Id": {
					"shape": "String"
				},
				"MD5OfMessageAttributes": {
					"shape": "String"
				},
				"MD5OfMessageBody": {
					"shape": "String"
				},
				"MD5OfMessageSystemAttributes": {
					"shape": "String"
				},
				"MessageId": {
					"shape": "String"
				},
				"SequenceNumber": {
					"shape": "String"
				}
			}
		},
		"SendMessageBatchResultEntryList": {
			"name": "SendMessageBatchResultEntryList",
			"type": "list",
			"member": {
				"shape": "SendMessageBatchResultEntry"
			},
			"flattened": true
		},
		"SendMessageRequest": {
			"name": "SendMessageRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"MessageBody"
			],
			"memberOrder": [
				"DelaySeconds",
				"MessageAttributes",
				"MessageBody",
				"MessageDeduplicationId",
				"MessageGroupId",
				"MessageSystemAttributes",
				"QueueUrl"
			],
			"members": {
				"DelaySeconds": {
					"shape": "NullableInteger"
				},
				"MessageAttributes": {
					"shape": "MessageBodyAttributeMap"
				},
				"MessageBody": {
					"shape": "String"
				},
				"MessageDeduplicationId": {
					"shape": "String"
				},
				"MessageGroupId": {
					"shape": "String"
				},
				"MessageSystemAttributes": {
					"shape": "MessageBodySystemAttributeMap"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"SendMessageResult": {
			"name": "SendMessageResult",
			"type": "structure",
			"memberOrder": [
				"MD5OfMessageAttributes",
				"MD5OfMessageBody",
				"MD5OfMessageSystemAttributes",
				"MessageId",
				"SequenceNumber"
			],
			"members": {
				"MD5OfMessageAttributes": {
					"shape": "String"
				},
				"MD5OfMessageBody": {
					"shape": "String"
				},
				"MD5OfMessageSystemAttributes": {
					"shape": "String"
				},
				"MessageId": {
					"shape": "String"
				},
				"SequenceNumber": {
					"shape": "String"
				}
			}
		},
		"SetQueueAttributesRequest": {
			"name": "SetQueueAttributesRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Attributes"
			],
			"memberOrder": [
				"Attributes",
				"QueueUrl"
			],
			"members": {
				"Attributes": {
					"shape": "QueueAttributeMap"
				},
				"QueueUrl": {
					"shape": "String"
				}
			}
		},
		"StartMessageMoveTaskRequest": {
			"name": "StartMessageMoveTaskRequest",
			"type": "structure",
			"required": [
				"SourceArn"
			],
			"memberOrder": [
				"DestinationArn",
				"MaxNumberOfMessagesPerSecond",
				"SourceArn"
			],
			"members": {
				"DestinationArn": {
					"shape": "String"
				},
				"MaxNumberOfMessagesPerSecond": {
					"shape": "NullableInteger"
				},
				"SourceArn": {
					"shape": "String"
				}
			}
		},
		"StartMessageMoveTaskResult": {
			"name": "StartMessageMoveTaskResult",
			"type": "structure",
			"memberOrder": [
				"TaskHandle"
			],
			"members": {
				"TaskHandle": {
					"shape": "String"
				}
			}
		},
		"String": {
			"name": "String",
			"type": "string"
		},
		"StringList": {
			"name": "StringList",
			"type": "list",
			"member": {
				"shape": "String"
			}
		},
		"TagKey": {
			"name": "TagKey",
			"type": "string"
		},
		"TagKeyList": {
			"name": "TagKeyList",
			"type": "list",
			"member": {
				"shape": "TagKey"
			},
			"flattened": true
		},
		"TagMap": {
			"name": "TagMap",
			"type": "map",
			"key": {
				"shape": "TagKey"
			},
			"value": {
				"shape": "TagValue"
			},
			"flattened": true
		},
		"TagQueueRequest": {
			"name": "TagQueueRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"Tags"
			],
			"memberOrder": [
				"QueueUrl",
				"Tags"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				},
				"Tags": {
					"shape": "TagMap"
				}
			}
		},
		"TagValue": {
			"name": "TagValue",
			"type": "string"
		},
		"Token": {
			"name": "Token",
			"type": "string"
		},
		"TooManyEntriesInBatchRequest": {
			"name": "TooManyEntriesInBatchRequest",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"UnsupportedOperation": {
			"name": "UnsupportedOperation",
			"type": "structure",
			"memberOrder": [
				"message"
			],
			"members": {
				"message": {
					"shape": "ExceptionMessage"
				}
			},
			"exception": true
		},
		"UntagQueueRequest": {
			"name": "UntagQueueRequest",
			"type": "structure",
			"required": [
				"QueueUrl",
				"TagKeys"
			],
			"memberOrder": [
				"QueueUrl",
				"TagKeys"
			],
			"members": {
				"QueueUrl": {
					"shape": "String"
				},
				"TagKeys": {
					"shape": "TagKeyList"
				}
			}
		}
	},
	"pagination": {
		"ListDeadLetterSourceQueues": {
			"inputToken": "NextToken",
			"outputToken": "NextToken",
			"limitKey": "MaxResults",
			"resultKey": "queueUrls"
		},
		"ListQueues": {
			"inputToken": "NextToken",
			"outputToken": "NextToken",
			"limitKey": "MaxResults",
			"resultKey": "QueueUrls"
		}
	}
}`
	if err := decodeRegistry([]byte(raw), &Default); err != nil {
		panic(err)
	}
}
